# Generated by Django 6.0.5 on 2026-05-09 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('status', models.CharField(default='Present', max_length=50)),
                ('pay', models.CharField(max_length=50)),
                ('days', models.IntegerField(default=0)),
                ('avatar', models.CharField(max_length=10)),
            ],
        ),
    ]
