# Generated by Django 6.0.5 on 2026-05-09 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0002_alter_worker_options_remove_worker_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='location',
            field=models.CharField(default='Farm Main Area', max_length=100),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='task_type',
            field=models.CharField(default='General Work', max_length=100),
        ),
    ]
